apiVersion: v1
kind: Service
metadata:
  name: echo-leaf-1
  namespace: echo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: echo-leaf-1
  sessionAffinity: None
  type: ClusterIP
